# Create App using:
#  cs app create shared/boutique app.yaml
endpoints:
- name: shop
  http:
    routes:
    - path_prefix: /
      backend:
        target: app
        port: frontend
workspaces:
- name: app
  ports:
  - name: frontend
    port: 8000
    protocol: HTTP/TCP
  checkouts:
  - path: boutique
    repo:
      git: https://github.com/crafting-demo/boutique
  packages:
  - name: golang
    version: ~1.18
  - name: nodejs
    version: ~16
  - name: openjdk
    version: ~14
  base_snapshot: shared/base-boutique-r1
  home_snapshot: shared/home-boutique-r1
  env:
  - GOOGLE_APPLICATION_CREDENTIALS=/run/sandbox/fs/secrets/shared/shared/gcp-account.json
  - KUBECONFIG=/run/sandbox/fs/secrets/shared/shared/kubeconfig-demo1.yaml
  - APP_NS=${SANDBOX_APP}-${SANDBOX_ID}
  probes:
    readiness:
    - name: frontend
      http_get:
        port: 8000
        path: /
resources:
- name: kubernetes
  brief: The deployment in the Kubernetes cluster
  details: |
    The deployment is in namespace `{{data.namespace}}`.
  handlers:
    on_create:
      max_retries: 3
      timeout: 300s
      save_state: true
      use_workspace:
        name: app
        run:
          dir: boutique
          cmd: .sandbox/deploy.sh
    on_suspend:
      max_retries: 1
      timeout: 300s
      use_workspace:
        name: app
        run:
          dir: boutique
          cmd: .sandbox/scale.sh 0
    on_resume:
      max_retries: 3
      timeout: 300s
      use_workspace:
        name: app
        run:
          dir: boutique
          cmd: .sandbox/scale.sh 1
    on_delete:
      max_retries: 3
      timeout: 300s
      use_workspace:
        name: app
        run:
          dir: boutique
          cmd: .sandbox/undeploy.sh
